### ISSUE TITLE
dmaas-operator keep restarting

### ISSUE THREAD

**Issue by mynktl** [mayadata-io/dmaas-operator#23]
On creation of dmaas-backup resource, dmaas-operator get keep restarting and panic observed in logs.
```
/home/travis/gopath/src/github.com/mayadata-io/dmaas-operator/pkg/controller/base_controller.go:116 +0x1c2
created by github.com/mayadata-io/dmaas-operator/pkg/controller.(*controller).Run
/home/travis/gopath/src/github.com/mayadata-io/dmaas-operator/pkg/controller/base_controller.go:117 +0x82
github.com/mayadata-io/dmaas-operator/pkg/controller.(*controller).Run.func2(0xc0003e1d80, 0x18157e0, 0xc0003dca40, 0xc0003a8ec4)
/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:88
k8s.io/apimachinery/pkg/util/wait.Until(...)
/home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0003a7fa0, 0x2540be400, 0x0, 0xc0003afd01, 0xc000096b40)
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x130b322] goroutine 180 [running]: k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0) /home/travis/gopath/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/runtime/runtime.go:55 +0x105 panic(0x143a200, 0x225c450) /home/travis/.gimme/versions/go1.14.7.linux.amd64/src/runtime/panic.go:969
``` 
Initial observation:
- dmaas-operator is receiving velero-schedule with empty creationTimestamp on schedule creation.

**Comment by mynktl** [comment]
![image (1)](https://user-images.githubusercontent.com/33252549/98339910-7b0f8380-2032-11eb-9f4e-0447b4d8a6f7.png)

**Comment by niladrih** [comment]
`get dmaasbackup` output from the cluster in the above screenshot.
```
 » kubectl -n maya-system get dmaasbackup                             [cmd:loki]
 NAME        AGE
 sch-eeohw   2d20h
 sch-sjvwr   2d20h
 sch-vsvth   2d20h
```
